// Generated by scripts/sync-verified-combat-mechanics.mjs.
// Source sha256: 6e153052b3d24151d849856a7f749bd6ec6c77a526f32ecb8f5a1197e4062274
// Do not edit this file directly.

export const Q16_SCALE = 65_536n;
export const Q16_HALF = 32_768n;
export const Q16_ONE = Q16_SCALE;
export const Q16_ZERO = 0n;

function assertFiniteNumber(value, label) {
  const number = Number(value);
  if (!Number.isFinite(number)) {
    throw new TypeError(`${label} must be finite, got ${value}`);
  }
  return number;
}

export function qFromInt(value) {
  return BigInt(value) << 16n;
}

// MyFloat.op_Implicit(float) performs a float32 multiply by 65536 and truncates.
export function qFromFloat(value) {
  const number = assertFiniteNumber(value, 'float');
  const scaled = Math.fround(Math.fround(number) * 65_536);
  return BigInt(Math.trunc(scaled));
}

export function qFromBasisPoints(value) {
  return qDiv(qFromInt(value), qFromInt(10_000));
}

export function qAdd(left, right) {
  return left + right;
}

export function qSub(left, right) {
  return left - right;
}

// This is equivalent to the split-word multiply at GameAssembly RVA 0x11A3100.
export function qMul(left, right) {
  return (left * right) >> 16n;
}

export function qDiv(left, right) {
  if (right === 0n) {
    throw new RangeError('Q16 division by zero');
  }
  return (left << 16n) / right;
}

export function qMin(left, right) {
  return left < right ? left : right;
}

export function qMax(left, right) {
  return left > right ? left : right;
}

export function qClamp(value, minimum, maximum) {
  return qMin(qMax(value, minimum), maximum);
}

export function qToNumber(raw) {
  return Number(raw) / 65_536;
}

export function qToFloat32(raw) {
  return Math.fround(qToNumber(raw));
}

export function qToInt(raw) {
  return raw >> 16n;
}

export function roundToEven(value) {
  const number = assertFiniteNumber(value, 'round value');
  const negative = number < 0;
  const absolute = Math.abs(number);
  const floor = Math.floor(absolute);
  const fraction = absolute - floor;
  let rounded = floor;
  if (fraction > 0.5 || (fraction === 0.5 && floor % 2 === 1)) {
    rounded += 1;
  }
  return negative ? -rounded : rounded;
}

// FormulaUtility converts MyFloat to float before calling its midpoint-to-even helper.
export function runtimeIntegerize(raw) {
  return BigInt(roundToEven(qToFloat32(raw)));
}

function qRatio(value, defaultValue = 0) {
  return qFromFloat(value ?? defaultValue);
}

function qFactor(value, defaultValue = 1) {
  return qFromFloat(value ?? defaultValue);
}

function qNonNegativeViaFloat(raw) {
  return qFromFloat(Math.max(0, qToFloat32(raw)));
}

function step(name, raw, extra = {}) {
  return {
    name,
    raw: raw.toString(),
    value: qToNumber(raw),
    ...extra,
  };
}

function resultWithTrace(mode, raw, trace, extra = {}) {
  return {
    mode,
    raw: raw.toString(),
    value: qToNumber(raw),
    integer: runtimeIntegerize(raw).toString(),
    trace,
    ...extra,
  };
}

export function attackRatioBaseRaw(attack, ratioBasisPoints) {
  return qDiv(qMul(qFromFloat(attack), qFromInt(ratioBasisPoints)), qFromInt(10_000));
}

export function attackRatioBase(attack, ratioBasisPoints) {
  const raw = attackRatioBaseRaw(attack, ratioBasisPoints);
  return step('attack_ratio_base', raw, { attack, ratioBasisPoints });
}

// element_formula 107205 and 119 both reduce to marks * ATK * coefficient / 10000.
// Their difference is where the mark count comes from: consumed pack count vs held layers.
export function tuningMarkBaseRaw(attack, markCount, coefficientRaw) {
  const count = Number(markCount);
  if (!Number.isInteger(count) || count < 0) {
    throw new TypeError(`markCount must be a non-negative integer, got ${markCount}`);
  }
  return qMul(qFromInt(count), attackRatioBaseRaw(attack, coefficientRaw));
}

export function tuningMarkBase(attack, markCount, coefficientRaw) {
  const raw = tuningMarkBaseRaw(attack, markCount, coefficientRaw);
  return step('tuning_mark_base', raw, {
    attack,
    markCount,
    coefficientRaw,
    coefficientPerMark: Number(coefficientRaw) / 10_000,
  });
}

function resolveBaseRaw(input) {
  if (input.baseRaw != null) {
    return BigInt(input.baseRaw);
  }
  if (input.baseFormula != null) {
    return qFromFloat(input.baseFormula);
  }
  if (input.attack != null && input.ratioBasisPoints != null) {
    return attackRatioBaseRaw(input.attack, input.ratioBasisPoints);
  }
  throw new TypeError('provide baseRaw, baseFormula, or attack + ratioBasisPoints');
}

function calculateBase(input, trace) {
  const formulaRaw = resolveBaseRaw(input);
  trace.push(step('formula_output', formulaRaw));
  const minimumRaw = qMax(formulaRaw, Q16_ONE);
  trace.push(step('formula_minimum_1', minimumRaw));
  const baseRaw = qMul(minimumRaw, qFactor(input.worldEventConflictPer));
  trace.push(step('world_event_conflict', baseRaw, {
    factor: input.worldEventConflictPer ?? 1,
  }));
  return baseRaw;
}

export function calculateDefenseFactor(input = {}) {
  const level = Number(input.targetLevel ?? 1);
  const physicalAfterFlat = qToInt(qMax(
    Q16_ZERO,
    qSub(qFromFloat(input.targetDefense ?? 0), qFromFloat(input.physicalPiercing ?? 0)),
  ));
  const magicAfterFlat = qToInt(qMax(
    Q16_ZERO,
    qSub(qFromFloat(input.targetMagicDefense ?? 0), qFromFloat(input.magicPiercing ?? 0)),
  ));
  const physicalPenetration = input.physicalPenetrationBasisPoints != null
    ? qFromBasisPoints(input.physicalPenetrationBasisPoints)
    : qRatio(input.physicalPenetration);
  const magicPenetration = input.magicPenetrationBasisPoints != null
    ? qFromBasisPoints(input.magicPenetrationBasisPoints)
    : qRatio(input.magicPenetration);
  const effectivePhysical = qMul(
    qFromInt(physicalAfterFlat),
    qSub(Q16_ONE, physicalPenetration),
  );
  const effectiveMagic = qMul(
    qFromInt(magicAfterFlat),
    qSub(Q16_ONE, magicPenetration),
  );
  const numerator = qFromInt(5 * (level + 100));
  const raw = qDiv(numerator, qAdd(qAdd(numerator, effectivePhysical), effectiveMagic));
  return {
    raw,
    value: qToNumber(raw),
    targetLevel: level,
    physicalAfterFlat: physicalAfterFlat.toString(),
    magicAfterFlat: magicAfterFlat.toString(),
    effectivePhysical: step('effective_physical_defense', effectivePhysical),
    effectiveMagic: step('effective_magic_defense', effectiveMagic),
  };
}

export function calculateElementFactor(input = {}) {
  const scale = qFactor(input.elementCalculationFactor);
  const raw = qNonNegativeViaFloat(qSub(
    qAdd(Q16_ONE, qMul(qRatio(input.attackerElementUp), scale)),
    qMul(qRatio(input.targetElementDefense), scale),
  ));
  return step('element_factor', raw);
}

export function calculatePhysicalMagicFactor(input = {}) {
  const physicalRatio = qRatio(input.physicalRatio);
  const magicRatio = qRatio(input.magicRatio);
  let raw = Q16_ONE;
  raw = qAdd(raw, qMul(qRatio(input.attackerPhysicalUp), physicalRatio));
  raw = qAdd(raw, qMul(qRatio(input.attackerMagicUp), magicRatio));
  raw = qSub(raw, qMul(qRatio(input.targetPhysicalDown), physicalRatio));
  raw = qSub(raw, qMul(qRatio(input.targetMagicDown), magicRatio));
  return step('physical_magic_factor', qNonNegativeViaFloat(raw));
}

export function calculateGeneralFactor(input = {}) {
  const raw = qNonNegativeViaFloat(qSub(
    qAdd(Q16_ONE, qRatio(input.attackerDamageUp)),
    qRatio(input.targetDamageDown),
  ));
  return step('general_factor', raw);
}

export function calculateSkillTagFactor(tags = []) {
  let raw = Q16_ONE;
  const factors = [];
  for (const tag of tags) {
    // Runtime adds both properties. Target-side reductions are signed in config.
    const factorRaw = qAdd(
      qAdd(Q16_ONE, qRatio(tag.attackerUp)),
      qRatio(tag.targetSigned),
    );
    raw = qMul(raw, factorRaw);
    factors.push(step(tag.name ?? `tag_${factors.length + 1}`, factorRaw));
  }
  return {
    ...step('skill_tag_factor', raw),
    factors,
  };
}

export function criticalFactor(input = {}) {
  if (!input.critical) {
    return step('critical_factor', Q16_ONE, { critical: false });
  }
  const raw = qMax(
    qFromFloat(0.1),
    qSub(qRatio(input.criticalDamage, 1), qRatio(input.targetCriticalDamageDown)),
  );
  return step('critical_factor', raw, { critical: true });
}

export function isCriticalHit(input = {}) {
  const chance = qSub(qRatio(input.criticalRate), qRatio(input.targetCriticalRateDefense));
  return qRatio(input.randomRoll) < chance;
}

export function levelPressureFromTable(attackerLevel, targetLevel, table) {
  const id = 1_000 + Number(targetLevel) - Number(attackerLevel);
  if (table instanceof Map) {
    return table.get(id) ?? 1;
  }
  return table?.[id] ?? table?.[String(id)] ?? 1;
}

export function calculateLevelPressureFactor(input = {}) {
  const attackerLevel = Number(input.attackerLevel ?? 1);
  const targetLevel = Number(input.targetLevel ?? 1);
  const applies = input.attackerIsPlayer !== false
    && input.targetIsEnemy !== false
    && Number(input.enemyPackLevelPressureType ?? 1) === 1
    && targetLevel > attackerLevel;
  const tableId = 1_000 + targetLevel - attackerLevel;
  return {
    applies,
    tableId: applies ? tableId : null,
    factor: applies
      ? levelPressureFromTable(attackerLevel, targetLevel, input.table)
      : 1,
  };
}

function applyFactor(raw, factorRaw, name, trace, extra = {}) {
  const next = qMul(raw, factorRaw);
  trace.push(step(name, next, extra));
  return next;
}

function applyCommonPostChain(raw, input, trace, { shields = true } = {}) {
  const restrained = applyFactor(
    raw,
    qFromFloat(1 + Number(input.restraintDelta ?? 0)),
    'restraint',
    trace,
    { delta: input.restraintDelta ?? 0 },
  );
  let current = qMax(Q16_ONE, restrained);
  trace.push(step('minimum_damage_before_global', current));
  if (!input.blockMiscellaneous) {
    current = applyFactor(
      current,
      qFactor(input.miscellaneous),
      'miscellaneous',
      trace,
      { factor: input.miscellaneous ?? 1 },
    );
  }
  if (input.inWeakState) {
    current = applyFactor(
      current,
      qAdd(Q16_ONE, qRatio(input.breakDamageUp)),
      'break_damage_up',
      trace,
      { bonus: input.breakDamageUp ?? 0 },
    );
  }
  const preShieldRaw = current;
  let remainingShields = [];
  let remainingHitCountShields = [];
  let hitCountBlocked = false;
  if (shields) {
    const shieldResult = applyRuntimeShields(current, {
      hitCountShields: input.hitCountShields ?? [],
      valueShields: input.valueShields ?? input.shields ?? [],
      outputType: Number(input.outputType ?? 1),
      outputElement: Number(input.outputElement ?? 0),
    });
    current = shieldResult.damageRaw;
    remainingShields = shieldResult.remainingValueShields;
    remainingHitCountShields = shieldResult.remainingHitCountShields;
    hitCountBlocked = shieldResult.hitCountBlocked;
    trace.push(step('after_shields', current, {
      absorbedRaw: shieldResult.absorbedRaw.toString(),
      hitCountBlocked,
      remainingHitCountShields: remainingHitCountShields.map((shield) => shield.count),
      remainingShields: remainingShields.map((value) => value.toString()),
    }));
  }
  if (input.minimumRemainingHp != null && input.currentHp != null) {
    const maximumDamage = qMax(
      Q16_ZERO,
      qSub(qFromFloat(input.currentHp), qFromFloat(input.minimumRemainingHp)),
    );
    current = qMin(current, maximumDamage);
    trace.push(step('minimum_hp_protection', current));
  }
  const integer = runtimeIntegerize(current);
  const integerizedRaw = qFromInt(integer);
  trace.push(step('runtime_integerize', integerizedRaw, { integer: integer.toString() }));
  return {
    raw: integerizedRaw,
    preShieldRaw,
    remainingShields,
    remainingHitCountShields,
    hitCountBlocked,
  };
}

function normalizeShieldTypes(shield) {
  return shield?.outputTypes ?? shield?.damageTypes ?? shield?.types ?? null;
}

function normalizeShieldElements(shield) {
  return shield?.elementTypes ?? shield?.elements ?? null;
}

export function shieldMatches(shield, outputType, outputElement) {
  const types = normalizeShieldTypes(shield);
  const elements = normalizeShieldElements(shield);
  if (!Array.isArray(types) || types.length === 0) return true;

  for (let index = 0; index < types.length; index += 1) {
    const acceptedType = Number(types[index]);
    if (acceptedType === outputType || acceptedType === 9) {
      const acceptedElement = Number(elements?.[index] ?? 10);
      if (acceptedElement === outputElement || acceptedElement === 10) return true;
    }
    // The runtime treats the first -1 as an unconditional wildcard. Shield damage
    // (type 11) also bypasses the element filter.
    if (Number(types[0]) === -1 || outputType === 11) return true;
  }
  return false;
}

function shieldValueRaw(shield) {
  if (typeof shield === 'bigint') return shield;
  if (shield?.raw != null) return BigInt(shield.raw);
  return qFromFloat(shield?.value ?? shield);
}

export function applySequentialShields(
  damageRaw,
  shields,
  { outputType = 1, outputElement = 0 } = {},
) {
  let current = damageRaw;
  let absorbed = Q16_ZERO;
  const remaining = [];
  for (const shield of shields) {
    const shieldRaw = shieldValueRaw(shield);
    if (current === Q16_ZERO || !shieldMatches(shield, outputType, outputElement)) {
      remaining.push(shieldRaw);
      continue;
    }
    const consumed = qMin(current, shieldRaw);
    absorbed = qAdd(absorbed, consumed);
    current = qSub(current, consumed);
    remaining.push(qSub(shieldRaw, consumed));
  }
  return { damageRaw: current, absorbedRaw: absorbed, remaining };
}

export function applyRuntimeShields(damageRaw, options = {}) {
  const outputType = Number(options.outputType ?? 1);
  const outputElement = Number(options.outputElement ?? 0);
  const hitCountShields = options.hitCountShields ?? [];
  let hitCountBlocked = false;
  const remainingHitCountShields = hitCountShields.map((shield) => {
    const count = Number(shield?.count ?? shield?.value ?? shield ?? 0);
    if (count > 0 && shieldMatches(shield, outputType, outputElement)) {
      hitCountBlocked = true;
      return typeof shield === 'object' && shield !== null
        ? { ...shield, count: count - 1 }
        : { count: count - 1 };
    }
    return typeof shield === 'object' && shield !== null
      ? { ...shield, count }
      : { count };
  });

  if (hitCountBlocked) {
    return {
      damageRaw: Q16_ZERO,
      absorbedRaw: damageRaw,
      hitCountBlocked: true,
      remainingHitCountShields,
      remainingValueShields: (options.valueShields ?? []).map(shieldValueRaw),
    };
  }

  const valueResult = applySequentialShields(
    damageRaw,
    options.valueShields ?? [],
    { outputType, outputElement },
  );
  return {
    damageRaw: valueResult.damageRaw,
    absorbedRaw: valueResult.absorbedRaw,
    hitCountBlocked: false,
    remainingHitCountShields,
    remainingValueShields: valueResult.remaining,
  };
}

export function calculateNormalDamage(input = {}) {
  const trace = [];
  let raw = calculateBase(input, trace);
  const defense = calculateDefenseFactor(input);
  raw = applyFactor(raw, defense.raw, 'defense', trace, {
    physicalAfterFlat: defense.physicalAfterFlat,
    magicAfterFlat: defense.magicAfterFlat,
  });
  const element = calculateElementFactor(input);
  raw = applyFactor(raw, BigInt(element.raw), 'element', trace);
  const physicalMagic = calculatePhysicalMagicFactor(input);
  raw = applyFactor(raw, BigInt(physicalMagic.raw), 'physical_magic', trace);
  const general = calculateGeneralFactor(input);
  raw = applyFactor(raw, BigInt(general.raw), 'general', trace);
  const skillTags = calculateSkillTagFactor(input.skillTags);
  raw = applyFactor(raw, BigInt(skillTags.raw), 'skill_tags', trace, {
    factors: skillTags.factors,
  });
  raw = applyFactor(raw, qFactor(input.hitLocationRatio), 'hit_location', trace);
  const critical = criticalFactor(input);
  raw = applyFactor(raw, BigInt(critical.raw), 'critical', trace, {
    critical: critical.critical,
  });
  raw = applyFactor(raw, qFactor(input.levelPressure), 'level_pressure', trace);
  const post = applyCommonPostChain(raw, input, trace, { shields: true });
  return resultWithTrace('normal', post.raw, trace, {
    preShieldRaw: post.preShieldRaw.toString(),
    hitCountBlocked: post.hitCountBlocked,
    remainingHitCountShields: post.remainingHitCountShields,
    remainingShields: post.remainingShields.map((value) => value.toString()),
  });
}

export function calculateMasteryCoefficient(input = {}) {
  const [c0 = 0, c1 = 0, c2 = 0.002] = input.masteryConstant ?? [0, 0, 0.002];
  const level = Number(input.attackerLevel ?? 1);
  const exponent = Number(input.masteryPowExponent ?? 2);
  const powered = Math.trunc(Math.pow(level, exponent));
  const linear = Math.fround(Math.fround(level) * Math.fround(c1));
  const poweredTerm = Math.fround(Math.fround(powered) * Math.fround(c0));
  const firstSum = Math.fround(linear + poweredTerm);
  return Math.fround(firstSum + Math.fround(c2));
}

export function calculateStackOverLimitDamage(input = {}) {
  const trace = [];
  const markMode = input.consumedMarks != null
    ? 'consumed'
    : input.heldMarks != null
      ? 'held'
      : null;
  const markCount = markMode === 'consumed' ? input.consumedMarks : input.heldMarks;
  const defaultCoefficientRaw = markMode === 'held' ? 308 : null;
  const coefficientRaw = input.overlimitCoefficientRaw
    ?? input.markCoefficientRaw
    ?? defaultCoefficientRaw;
  if (markMode && coefficientRaw == null) {
    throw new TypeError('consumedMarks requires overlimitCoefficientRaw or markCoefficientRaw');
  }
  const baseInput = markMode
    ? {
        ...input,
        baseRaw: tuningMarkBaseRaw(input.attack, markCount, coefficientRaw),
      }
    : input;
  let raw = calculateBase(baseInput, trace);
  if (markMode) {
    trace[0] = {
      ...trace[0],
      formula: markMode === 'consumed'
        ? 'CONSUME_PACK_ELEMENT_COUNT[M] * ATK * A / 10000'
        : 'ELEMENT_LAYERS[H] * ATK * I / 10000',
      markMode,
      markCount,
      coefficientRaw: Number(coefficientRaw),
      coefficientPerMark: Number(coefficientRaw) / 10_000,
    };
  }
  const general = calculateGeneralFactor(input);
  raw = applyFactor(raw, BigInt(general.raw), 'general', trace);
  const skillTags = calculateSkillTagFactor(input.skillTags);
  raw = applyFactor(raw, BigInt(skillTags.raw), 'skill_tags', trace, {
    factors: skillTags.factors,
  });
  raw = applyFactor(raw, qFactor(input.hitLocationRatio), 'hit_location', trace);
  raw = applyFactor(
    raw,
    qAdd(qRatio(input.mastery), qFromInt(300)),
    'mastery_plus_300',
    trace,
  );
  const coefficient = calculateMasteryCoefficient(input);
  raw = applyFactor(raw, qFromFloat(coefficient), 'mastery_coefficient', trace, {
    coefficient,
    masteryConstant: input.masteryConstant ?? [0, 0, 0.002],
  });
  raw = applyFactor(raw, qFactor(input.levelPressure), 'level_pressure', trace);
  const post = applyCommonPostChain(raw, { ...input, critical: false }, trace, { shields: true });
  return resultWithTrace('stack_over_limit', post.raw, trace, {
    preShieldRaw: post.preShieldRaw.toString(),
    hitCountBlocked: post.hitCountBlocked,
    remainingHitCountShields: post.remainingHitCountShields,
    remainingShields: post.remainingShields.map((value) => value.toString()),
    markScaling: markMode ? {
      mode: markMode,
      count: Number(markCount),
      coefficientRaw: Number(coefficientRaw),
      coefficientPerMark: Number(coefficientRaw) / 10_000,
      consumesMarks: markMode === 'consumed',
    } : null,
  });
}

export function calculateRealDamage(input = {}) {
  const trace = [];
  let raw = calculateBase(input, trace);
  raw = applyFactor(raw, Q16_ONE, 'real_constant_1', trace);
  raw = applyFactor(raw, qFactor(input.hitLocationRatio), 'hit_location', trace);
  if (!input.blockMiscellaneous) {
    raw = applyFactor(raw, qFactor(input.miscellaneous), 'miscellaneous', trace, {
      factor: input.miscellaneous ?? 1,
    });
  }
  if (input.inWeakState) {
    raw = applyFactor(
      raw,
      qAdd(Q16_ONE, qRatio(input.breakDamageUp)),
      'break_damage_up',
      trace,
    );
  }
  const preShieldRaw = raw;
  if (input.minimumRemainingHp != null && input.currentHp != null) {
    raw = qMin(
      raw,
      qMax(Q16_ZERO, qSub(qFromFloat(input.currentHp), qFromFloat(input.minimumRemainingHp))),
    );
    trace.push(step('minimum_hp_protection', raw));
  }
  const integer = runtimeIntegerize(raw);
  const integerizedRaw = qFromInt(integer);
  trace.push(step('runtime_integerize', integerizedRaw, { integer: integer.toString() }));
  return resultWithTrace('real', integerizedRaw, trace, {
    preShieldRaw: preShieldRaw.toString(),
    shieldsBypassed: true,
  });
}

export function calculateWeaknessDamage(input = {}) {
  const trace = [];
  const pure = input.pure === true;
  if (input.inWeakState || (!pure && Number(input.outputType ?? 1) === 8)) {
    trace.push(step('weakness_skipped', Q16_ZERO, {
      reason: input.inWeakState ? 'target_already_in_weak_state' : 'dedicated_weakness_route',
    }));
    return {
      ...resultWithTrace(pure ? 'pure_weakness' : 'weakness', Q16_ZERO, trace),
      deducted: '0',
    };
  }
  if (pure && Number(input.worldEventConflictPer ?? 1) < 1) {
    trace.push(step('weakness_skipped', Q16_ZERO, {
      reason: 'world_event_conflict_below_1',
    }));
    return {
      ...resultWithTrace('pure_weakness', Q16_ZERO, trace),
      deducted: '0',
    };
  }

  const baseRaw = pure
    ? qMax(resolveBaseRaw(input), Q16_ONE)
    : input.outputDamageRaw != null
      ? BigInt(input.outputDamageRaw)
      : qFromFloat(input.outputDamage ?? 0);
  trace.push(step(pure ? 'pure_weakness_base_minimum_1' : 'hp_damage_before_shield', baseRaw));
  let raw = qFactor(input.typeMultiplier);
  trace.push(step('weakness_type', raw));
  raw = applyFactor(raw, qFactor(input.elementMultiplier), 'weakness_element', trace);
  raw = applyFactor(raw, baseRaw, 'weakness_base_applied', trace);
  if (!pure) {
    raw = applyFactor(
      raw,
      qFactor(input.weaknessSkillDamageUp),
      'weakness_skill_tag',
      trace,
    );
  }
  raw = applyFactor(
    raw,
    input.weakBreakDamageRateBasisPoints != null
      ? qFromBasisPoints(input.weakBreakDamageRateBasisPoints)
      : qFactor(input.weakBreakDamageRate),
    'weak_break_rate',
    trace,
  );
  if (input.maximum != null) {
    raw = qMin(raw, qFromFloat(input.maximum));
    trace.push(step('weakness_maximum', raw));
  }
  if (input.minimum != null) {
    raw = qMax(raw, qFromFloat(input.minimum));
    trace.push(step('weakness_minimum', raw));
  }
  const integer = runtimeIntegerize(raw);
  return {
    ...resultWithTrace(pure ? 'pure_weakness' : 'weakness', raw, trace),
    deducted: integer.toString(),
  };
}

export function calculateNormalWeaknessRecovery(input = {}) {
  const raw = qMul(
    qMul(qRatio(input.recoveryRate), qFromFloat(input.maximumWeakness ?? 0)),
    qFromFloat(input.deltaTime ?? 0),
  );
  return resultWithTrace('weakness_recovery', raw, [step('recovered', raw)], {
    recoveryDelay: Number(input.recoveryDelay ?? 0),
  });
}

export function calculateBreakWeakness(input = {}) {
  const maximum = qFromFloat(input.maximumWeakness ?? 0);
  const breakTime = Number(input.breakTime ?? 0);
  const elapsed = Number(input.elapsed ?? 0);
  const progress = breakTime > 0 ? Math.min(1, Math.max(0, elapsed / breakTime)) : 1;
  const raw = qMul(maximum, qFromFloat(progress));
  return resultWithTrace('break_weakness', raw, [step('linear_break_recovery', raw)], {
    progress,
    breakEndTime: Number(input.breakEndTime ?? 0),
    phase: elapsed < breakTime
      ? 'linear_recovery'
      : elapsed < breakTime + Number(input.breakEndTime ?? 0)
        ? 'break_end_wait'
        : 'normal',
  });
}

function clampSp(raw, maximumSp) {
  return qClamp(raw, Q16_ZERO, qFromFloat(maximumSp ?? Number.MAX_SAFE_INTEGER));
}

export function calculateAutoSp(input = {}) {
  const trace = [];
  const source = input.background ? input.sprSecBack : input.sprSec;
  let raw = qFromFloat(source ?? 0);
  trace.push(step(input.background ? 'spr_sec_back' : 'spr_sec', raw));
  const bonus = qAdd(
    qAdd(Q16_ONE, qRatio(input.spGetUp)),
    qRatio(input.spRetAuto ?? input.spGetUpAuto),
  );
  raw = applyFactor(raw, bonus, 'auto_sp_bonus', trace, { attributeKeys: ['SPGETUP', 'SPRET_AUTO'], legacyAlias: input.spRetAuto == null && input.spGetUpAuto != null ? 'SPGETUP_AUTO' : null });
  raw = applyFactor(raw, qFromFloat(input.tickSeconds ?? 0.1), 'tick_seconds', trace);
  const clamped = clampSp(raw, input.maximumSp);
  trace.push(step('sp_clamped', clamped));
  return resultWithTrace(input.background ? 'sp_auto_background' : 'sp_auto_foreground', clamped, trace);
}

export function calculateHitSp(input = {}) {
  const trace = [];
  const configValue = input.pet ? input.petRecoverSp : input.recoverSp;
  let raw = qDiv(qFromInt(configValue ?? 0), qFromInt(10_000));
  trace.push(step(input.pet ? 'pet_recover_sp' : 'hero_recover_sp', raw, {
    configValue: configValue ?? 0,
  }));
  const bonus = qAdd(
    qAdd(Q16_ONE, qRatio(input.spGetUp)),
    qRatio(input.spGetUpAttack),
  );
  raw = applyFactor(raw, bonus, 'hit_sp_bonus', trace);
  const clamped = clampSp(raw, input.maximumSp);
  trace.push(step('sp_clamped', clamped));
  return resultWithTrace(input.pet ? 'sp_hit_pet' : 'sp_hit_hero', clamped, trace, {
    intervalSeconds: Number(input.recoverInterval ?? 0) / 1_000,
    backgroundShare: input.pet ? 1 : 0.5,
  });
}
